spring.application.name=els-demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:els_demo;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ELS Configuration
els.access-type=WHITELIST
els.join.behavior=ID_ONLY

# Logging
logging.level.com.els=DEBUG
